/**
 * generate-docs.ts
 *
 * Writes four persistent documentation files to /docs/ in the repo:
 *   codebase.md     — folder structure, key files, patterns, danger zones
 *   workflow.md     — local setup, PR lifecycle, CI/CD, deploy
 *   domain.md       — business entities, glossary, domain rules
 *   system-design.md — tech stack, architecture, external deps
 *
 * These files are owned by the team — they should be reviewed and committed.
 * The onboarding session reads from /docs/ on subsequent runs instead of regenerating.
 */

import { readFile, readdir, stat, mkdir, writeFile } from "fs/promises";
import { join, extname, relative } from "path";
import type { RepoStructure } from "./analyze-repo.js";

export interface GeneratedDoc {
  fileName: string;
  path: string;
  content: string;
  wasWritten: boolean;
  error?: string;
}

export interface GenerateDocsResult {
  docs: GeneratedDoc[];
  docsDir: string;
  summary: string;
}

async function readFileSafe(p: string): Promise<string | null> {
  try {
    return await readFile(p, "utf-8");
  } catch {
    return null;
  }
}

async function readDirSafe(p: string): Promise<string[]> {
  try {
    return await readdir(p);
  } catch {
    return [];
  }
}

async function collectFiles(
  dir: string,
  ext: string,
  limit = 8
): Promise<{ path: string; content: string }[]> {
  const files: { path: string; content: string }[] = [];
  try {
    const entries = await readdir(dir);
    for (const entry of entries.slice(0, limit * 2)) {
      if (files.length >= limit) break;
      if (!entry.endsWith(ext)) continue;
      const content = await readFileSafe(join(dir, entry));
      if (content) files.push({ path: join(dir, entry), content: content.slice(0, 4000) });
    }
  } catch { /* dir doesn't exist */ }
  return files;
}

function timestamp(): string {
  return new Date().toISOString().split("T")[0];
}

function autoGeneratedHeader(repoName: string, docType: string): string {
  return `# ${docType} — ${repoName}

> AUTO-GENERATED on ${timestamp()} — review this file, correct anything wrong, and commit it.
> This file is used by the /onboarding skill to guide new engineers.

`;
}

// ─── codebase.md ─────────────────────────────────────────────────────────────

async function findJavaSourceRoot(repoPath: string): Promise<string | null> {
  // Maven convention: src/main/java
  const mavenRoot = join(repoPath, "src", "main", "java");
  try { await stat(mavenRoot); return mavenRoot; } catch { /* */ }
  // Gradle/other: src/main
  const gradleRoot = join(repoPath, "src", "main");
  try { await stat(gradleRoot); return gradleRoot; } catch { /* */ }
  return null;
}

async function getJavaPackages(javaRoot: string, repoPath: string): Promise<string[]> {
  const packages: string[] = [];
  async function walk(dir: string, depth: number): Promise<void> {
    if (depth > 4) return;
    let entries: string[];
    try { entries = await readdir(dir); } catch { return; }
    const javaFiles = entries.filter((e) => e.endsWith(".java"));
    if (javaFiles.length > 0) {
      packages.push(relative(javaRoot, dir).replace(/\//g, "."));
    }
    for (const entry of entries) {
      const full = join(dir, entry);
      let s; try { s = await stat(full); } catch { continue; }
      if (s.isDirectory()) await walk(full, depth + 1);
    }
  }
  await walk(javaRoot, 0);
  return packages.filter(Boolean).sort();
}

async function collectJavaFiles(javaRoot: string, limit = 8): Promise<{ path: string; content: string }[]> {
  const files: { path: string; content: string }[] = [];
  async function walk(dir: string): Promise<void> {
    if (files.length >= limit) return;
    let entries: string[];
    try { entries = await readdir(dir); } catch { return; }
    for (const entry of entries) {
      if (files.length >= limit) break;
      const full = join(dir, entry);
      let s; try { s = await stat(full); } catch { continue; }
      if (s.isDirectory()) { await walk(full); }
      else if (entry.endsWith(".java")) {
        const content = await readFileSafe(full);
        if (content) files.push({ path: full, content: content.slice(0, 3000) });
      }
    }
  }
  await walk(javaRoot);
  return files;
}

async function generateCodebaseMd(repoPath: string, analysis: RepoStructure, repoName: string): Promise<string> {
  const { techStack, keyDirs, testDirs, entryPoints, topLevelFiles } = analysis;
  const isJava = techStack.language === "java";
  const isRails = techStack.framework === "Ruby on Rails";

  // Collect source files based on language
  const modelFiles = isRails ? await collectFiles(join(repoPath, "app", "models"), ".rb", 5) : [];
  const serviceFiles = isRails ? await collectFiles(join(repoPath, "app", "services"), ".rb", 3) : [];
  const srcTsFiles = techStack.language === "typescript" ? await collectFiles(join(repoPath, "src"), ".ts", 5) : [];

  // Java: find real source root and packages
  const javaRoot = isJava ? await findJavaSourceRoot(repoPath) : null;
  const javaPackages = javaRoot ? await getJavaPackages(javaRoot, repoPath) : [];
  const javaFiles = javaRoot ? await collectJavaFiles(javaRoot, 6) : [];

  // Danger zones
  const dangerCandidates: string[] = [];
  if (isRails) {
    for (const f of [...modelFiles, ...serviceFiles]) {
      if (f.content.length > 3000) dangerCandidates.push(relative(repoPath, f.path));
    }
    dangerCandidates.push("app/models/company.rb (if exists — God model)", "config/routes.rb", "db/schema.rb");
  }
  if (isJava && techStack.extraTech.includes("Quartz Scheduler")) {
    dangerCandidates.push("Job configuration files (jobconfig.xml) — changing schedules affects production cron", "DAO classes — direct DB/MongoDB access, no ORM safety net");
  }

  const namingConventions = isRails
    ? "- Files: `snake_case.rb` · Classes: `PascalCase` · Methods: `snake_case`\n- Service objects: `NounVerbService` (e.g. `InvoiceCreationService`)\n- Tests: mirror the source path under `spec/`"
    : techStack.language === "typescript"
    ? "- Files: `kebab-case.ts` · Classes/interfaces: `PascalCase` · Functions: `camelCase`"
    : isJava
    ? "- Package: `com.company.module` · Classes: `PascalCase` · Methods: `camelCase`\n- Controllers: `*Resource.java` or `*Controller.java` · Jobs: `*Job.java` · DAOs: `*Dao.java`"
    : "Conventions not auto-detected — check your README or ask a senior engineer.";

  const commonPatterns = isRails
    ? `- **Service Objects** (\`app/services/\`) — business logic, not in controllers or models\n- **Workers** (\`app/workers/\`) — async jobs via ${techStack.extraTech.includes("Sidekiq") ? "Sidekiq" : "background processing"}\n- **Concerns** — shared behavior via modules\n- **Queries** (\`app/queries/\`) — complex ActiveRecord queries`
    : isJava && javaPackages.length > 0
    ? `Packages found under \`${javaRoot ? relative(repoPath, javaRoot) : "src"}\`:\n${javaPackages.slice(0, 10).map((p) => `- \`${p}\``).join("\n")}`
    : "_Check existing code and ask your team_";

  const keyFiles = isRails
    ? modelFiles.slice(0, 5).map((f) => `- \`${relative(repoPath, f.path)}\``).join("\n") || "_No model files found_"
    : isJava && javaFiles.length > 0
    ? javaFiles.slice(0, 6).map((f) => `- \`${relative(repoPath, f.path)}\``).join("\n")
    : srcTsFiles.slice(0, 5).map((f) => `- \`${relative(repoPath, f.path)}\``).join("\n") || "_No source files found_";

  return autoGeneratedHeader(repoName, "Codebase Guide") + `
## Folder Structure

${keyDirs.map((d) => `- \`${d}/\` — _inferred from project layout_`).join("\n") || "_No standard directories detected_"}
${isJava && javaRoot ? `\nMaven source root: \`${relative(repoPath, javaRoot)}/\`` : ""}

Top-level files: ${topLevelFiles.slice(0, 15).join(", ")}

## Entry Points

${entryPoints.length > 0 ? entryPoints.map((e) => `- \`${e}\``).join("\n") : isJava ? "_Java app — look for `web.xml` in `WebContent/WEB-INF/` or a `@ApplicationPath` annotation_" : "_Not auto-detected — check README_"}

## Key Files

${keyFiles}

## Naming Conventions

${namingConventions}

## Common Patterns

${commonPatterns}

## Danger Zones

These files/areas require senior review before touching:

${dangerCandidates.length > 0 ? dangerCandidates.map((d) => `- \`${d}\``).join("\n") : "_Treat all shared models and auth code with care_"}

- **Background job consumers / scheduled jobs** — silent failures, hard to debug
- **Authentication/authorization code** — a bug here affects all users
${isJava ? "- **`pom.xml` dependency changes** — can cause classpath conflicts, test with full build" : "- **Database migrations** — never run on production without review"}

## Test Structure

Test directories: ${testDirs.join(", ") || (isJava ? "`src/test/java/`" : "_not detected_")}
Test framework: ${techStack.testFramework ?? "_not detected_"}
`;
}

// ─── workflow.md ──────────────────────────────────────────────────────────────

async function generateWorkflowMd(repoPath: string, analysis: RepoStructure, repoName: string): Promise<string> {
  const { techStack } = analysis;
  const readme = await readFileSafe(join(repoPath, "README.md")) ?? "";
  const makefile = await readFileSafe(join(repoPath, "Makefile")) ?? "";

  // Extract setup commands from README/Makefile
  const hasDocker = analysis.techStack.hasDocker;
  const hasMakefile = makefile.length > 0;

  // Extract make targets for context
  const makeTargets = makefile
    ? makefile.match(/^[a-zA-Z][a-zA-Z0-9_-]+:/gm)?.map((t) => t.replace(":", "")).slice(0, 10) ?? []
    : [];

  const setupSteps = techStack.framework === "Ruby on Rails"
    ? `\`\`\`bash
${hasMakefile ? "make setup" : "bundle install\nbundle exec rake db:create db:migrate"}
${hasDocker ? "# or: docker-compose up" : ""}
\`\`\``
    : techStack.language === "typescript"
    ? `\`\`\`bash
${techStack.packageManager === "yarn" ? "yarn install" : "npm install"}
\`\`\``
    : techStack.language === "java"
    ? `\`\`\`bash
${hasMakefile ? `# Available make targets: ${makeTargets.join(", ")}\nmake <target>` : "mvn clean install"}
${hasDocker ? "# or: docker-compose up" : ""}
\`\`\``
    : hasDocker
    ? "```bash\ndocker-compose up\n```"
    : "_See README for setup steps_";

  const testCmd = techStack.testFramework === "RSpec"
    ? "`bundle exec rspec`"
    : techStack.testFramework === "Jest"
    ? `\`${techStack.packageManager === "yarn" ? "yarn test" : "npm test"}\``
    : techStack.testFramework === "pytest"
    ? "`pytest`"
    : techStack.testFramework === "JUnit"
    ? "`mvn test`"
    : techStack.testFramework === "go test"
    ? "`go test ./...`"
    : "_check README for test command_";

  return autoGeneratedHeader(repoName, "Engineering Workflow") + `
## Local Setup

${setupSteps}

Required services: ${[
    techStack.extraTech.includes("MySQL") || techStack.extraTech.some(t => t.includes("SQL")) ? "Database" : null,
    techStack.extraTech.includes("Redis") ? "Redis" : null,
    techStack.extraTech.includes("Sidekiq") ? "Sidekiq (background jobs)" : null,
    techStack.extraTech.includes("Karafka/Kafka") ? "Kafka" : null,
    techStack.extraTech.includes("Elasticsearch") ? "Elasticsearch" : null,
    analysis.techStack.hasDocker ? "Docker (or install services directly)" : null,
  ].filter(Boolean).join(", ") || "none auto-detected — check README"}

## Branch Naming

_Inferred pattern — confirm with your team:_
- Feature: \`feature/TICKET-ID-short-description\`
- Bug fix: \`fix/TICKET-ID-short-description\`
- Main branch: check \`git remote show origin\` for the default branch name

## PR Lifecycle

1. Branch off main/trunk
2. Make your changes + write tests
3. Run tests locally: ${testCmd}
4. Open PR — fill in the PR template if one exists (\`.github/PULL_REQUEST_TEMPLATE.md\`)
5. Request review from at least one team member
6. Address review comments
7. Merge (squash or merge commit — follow team convention)
8. Delete the branch

## CI/CD Pipeline

${techStack.hasCICD ? `CI platform: **${techStack.cicdPlatform}**\n\nThe pipeline runs on every PR push. Check the pipeline config for exact steps.` : "_No CI/CD configuration auto-detected — ask your team_"}

## Testing

Run tests before every push: ${testCmd}

${techStack.testFramework === "RSpec" ? "- Run a single file: `bundle exec rspec spec/path/to/file_spec.rb`\n- Run with line number: `bundle exec rspec spec/path/to/file_spec.rb:42`" : ""}

## Deployment

_Not auto-detected — ask your team how code reaches staging and production._

Common patterns in this tech stack:
${techStack.framework === "Ruby on Rails" ? "- Heroku, Render, or custom CI deploy script\n- Check `Procfile` or CI config for deploy steps" : ""}
${techStack.language === "typescript" ? "- Vercel, Railway, Fly.io, or Docker-based\n- Check CI config for deploy steps" : ""}

## If You Break Something

1. Don't panic — everyone breaks something
2. Revert your change immediately if in production
3. Ping your team lead in Slack
4. Write a brief incident note (what happened, what you reverted)
5. Fix forward after the fire is out
`;
}

// ─── domain.md ───────────────────────────────────────────────────────────────

async function generateDomainMd(repoPath: string, analysis: RepoStructure, repoName: string): Promise<string> {
  const isJava = analysis.techStack.language === "java";

  const modelFiles = analysis.techStack.framework === "Ruby on Rails"
    ? await collectFiles(join(repoPath, "app", "models"), ".rb", 10)
    : [];
  const srcFiles = analysis.techStack.language === "typescript"
    ? await collectFiles(join(repoPath, "src"), ".ts", 10)
    : [];

  // Java: look in src/main/java for model/entity classes
  let javaModelFiles: { path: string; content: string }[] = [];
  if (isJava) {
    const javaRoot = await findJavaSourceRoot(repoPath);
    if (javaRoot) {
      const modelsDir = join(javaRoot, "com", repoName.replace(/-/g, ""), "models");
      javaModelFiles = await collectJavaFiles(modelsDir, 10).catch(() => []);
      if (javaModelFiles.length === 0) {
        // Try common parent dirs
        javaModelFiles = await collectJavaFiles(javaRoot, 15);
        javaModelFiles = javaModelFiles.filter((f) =>
          f.path.includes("/models/") || f.path.includes("/entities/") || f.path.includes("/domain/")
        );
      }
    }
  }

  const entityFiles = [...modelFiles, ...srcFiles, ...javaModelFiles];
  const entityNames = entityFiles
    .map((f) => f.path.split("/").pop()?.replace(/\.(rb|ts|py|java|go)$/, "") ?? "")
    .filter(Boolean)
    .filter((n) => !["application", "concerns", "base", "abstract", "ApplicationResource", "ErrorResponse"].some((skip) => n.includes(skip)));

  return autoGeneratedHeader(repoName, "Domain Context") + `
## Core Domain Entities

_Inferred from model/source files — descriptions need human review:_

${entityNames.slice(0, 15).map((n) => `- **${n.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())}** (\`${n}\`) — _add description_`).join("\n") || "_No entities auto-detected_"}

## Key Business Concepts

_Fill this in with your team — this is the most valuable section for new engineers._

Examples:
- What does this product do for its users?
- What is the core data model / transaction?
- What are the key domain rules (e.g. "an invoice can only be finalized once")?

## Glossary

| Term | Meaning |
|------|---------|
| _add terms_ | _add definitions_ |

_Tip: Start with any word in the codebase that confused you on day one._

## Domain Rules (inferred from code)

_These need human review — inferences may be wrong:_

${analysis.techStack.framework === "Ruby on Rails" ? "- ActiveRecord validations in model files define data integrity rules\n- Callbacks (before_save, after_create) encode business side-effects\n- Service objects in app/services/ encode business workflows" : "_Review source files for business logic patterns_"}

## Key Relationships

_Add an entity relationship summary here — a diagram or a few bullet points is enough._
`;
}

// ─── system-design.md ────────────────────────────────────────────────────────

async function generateSystemDesignMd(repoPath: string, analysis: RepoStructure, repoName: string): Promise<string> {
  const { techStack } = analysis;

  const externalDeps: string[] = [];
  if (techStack.extraTech.includes("Elasticsearch")) externalDeps.push("Elasticsearch — full-text search");
  if (techStack.extraTech.includes("Redis")) externalDeps.push("Redis — caching and job queues");
  if (techStack.extraTech.includes("Sidekiq")) externalDeps.push("Sidekiq — async background processing");
  if (techStack.extraTech.includes("Karafka/Kafka")) externalDeps.push("Kafka — event streaming");
  if (techStack.extraTech.includes("MongoDB (Mongoid)")) externalDeps.push("MongoDB — document storage (alongside relational DB)");

  return autoGeneratedHeader(repoName, "System Design") + `
## Tech Stack

| Layer | Technology |
|-------|-----------|
| Language | ${techStack.language} |
| Framework | ${techStack.framework ?? "not detected"} |
| Package Manager | ${techStack.packageManager ?? "not detected"} |
| Test Framework | ${techStack.testFramework ?? "not detected"} |
| Docker | ${techStack.hasDocker ? "yes" : "not detected"} |
| CI/CD | ${techStack.hasCICD ? techStack.cicdPlatform : "not detected"} |
${techStack.extraTech.map((t) => `| Extra | ${t} |`).join("\n")}

## Architecture Overview

_Fill in: is this a monolith, microservice, or frontend app? How does it fit in the broader system?_

${techStack.framework === "Ruby on Rails" ? "This is a Rails application. It likely follows MVC with service objects for business logic." : ""}

## Service Boundaries

_If this repo calls other internal services or APIs, list them here._

| Service | How it's called | Purpose |
|---------|----------------|---------|
| _add_ | _REST / gRPC / Kafka_ | _add_ |

## External Dependencies

${externalDeps.length > 0 ? externalDeps.map((d) => `- ${d}`).join("\n") : "_None auto-detected_"}

## Data Flow

_Describe the main data flow for the most important operation in the system._

Example: User creates an Invoice → controller → InvoiceCreationService → Invoice model → job queued → email sent

## Infrastructure

${techStack.hasDocker ? "- Docker / docker-compose for local development" : ""}
${techStack.hasCICD ? `- ${techStack.cicdPlatform} for CI/CD` : ""}
_Add: hosting platform, database server, secrets management_

## Key Design Decisions

_This is the most valuable section — why is the system shaped this way?_

- _Add architectural decisions and the reason behind them_
- _Add things that seem odd but have a good reason_
`;
}

// ─── Writer ──────────────────────────────────────────────────────────────────

async function writeDoc(docsDir: string, fileName: string, content: string): Promise<GeneratedDoc> {
  const filePath = join(docsDir, fileName);
  try {
    await writeFile(filePath, content, "utf-8");
    return { fileName, path: filePath, content, wasWritten: true };
  } catch (e) {
    return { fileName, path: filePath, content, wasWritten: false, error: String(e) };
  }
}

export async function generateOnboardingDocs(
  repoPath: string,
  analysis: RepoStructure
): Promise<GenerateDocsResult> {
  const repoName = repoPath.split("/").pop() ?? "this-repo";
  const docsDir = join(repoPath, "docs");

  await mkdir(docsDir, { recursive: true });

  const [codebase, workflow, domain, systemDesign] = await Promise.all([
    generateCodebaseMd(repoPath, analysis, repoName),
    generateWorkflowMd(repoPath, analysis, repoName),
    generateDomainMd(repoPath, analysis, repoName),
    generateSystemDesignMd(repoPath, analysis, repoName),
  ]);

  const docs = await Promise.all([
    writeDoc(docsDir, "codebase.md", codebase),
    writeDoc(docsDir, "workflow.md", workflow),
    writeDoc(docsDir, "domain.md", domain),
    writeDoc(docsDir, "system-design.md", systemDesign),
  ]);

  const written = docs.filter((d) => d.wasWritten).length;
  const failed = docs.filter((d) => !d.wasWritten);

  const summary = [
    `✅ Generated ${written}/4 onboarding docs in ${docsDir}`,
    written > 0 ? "Files written: " + docs.filter((d) => d.wasWritten).map((d) => d.fileName).join(", ") : "",
    failed.length > 0 ? "⚠️  Failed: " + failed.map((d) => `${d.fileName} (${d.error})`).join(", ") : "",
    "",
    "⚠️  These files are AUTO-GENERATED. Review them, correct anything wrong, and commit to your repo.",
    "The onboarding session will use them from /docs/ on subsequent runs.",
  ]
    .filter(Boolean)
    .join("\n");

  return { docs, docsDir, summary };
}

// ─── Freshness check ─────────────────────────────────────────────────────────

export interface DocsFreshnessResult {
  isStale: boolean;
  staleDocs: { fileName: string; ageInDays: number }[];
  summary: string;
}

export async function checkDocsFreshness(
  repoPath: string,
  staleDaysThreshold = 90
): Promise<DocsFreshnessResult> {
  const docsDir = join(repoPath, "docs");
  const files = ["codebase.md", "workflow.md", "domain.md", "system-design.md"];
  const staleDocs: { fileName: string; ageInDays: number }[] = [];
  const now = Date.now();

  for (const file of files) {
    try {
      const info = await stat(join(docsDir, file));
      const ageInDays = Math.floor((now - info.mtimeMs) / (1000 * 60 * 60 * 24));
      if (ageInDays > staleDaysThreshold) {
        staleDocs.push({ fileName: file, ageInDays });
      }
    } catch {
      // file doesn't exist — not stale, just missing
    }
  }

  const isStale = staleDocs.length > 0;
  const summary = isStale
    ? `⚠️  ${staleDocs.length} doc(s) are older than ${staleDaysThreshold} days:\n` +
      staleDocs.map((d) => `  - ${d.fileName} (${d.ageInDays} days old)`).join("\n") +
      "\n\nConsider running `/onboarding refresh-docs` to regenerate."
    : `✅ All docs are fresh (under ${staleDaysThreshold} days old).`;

  return { isStale, staleDocs, summary };
}
