import { mkdir, writeFile, readdir } from "fs/promises";
import { join } from "path";

export interface SessionNotesInput {
  repoPath: string;
  engineerName?: string;
  language: "en" | "id";
  division: string;
  productName: string;
  topicsCovered: string[];
  openQuestions: string[];
  xpEarned: number;
  nextSteps: string[];
  freeformNotes?: string;
}

export interface SaveNotesResult {
  savedPath: string;
  success: boolean;
  error?: string;
}

function formatDate(): string {
  return new Date().toISOString().split("T")[0];
}

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function renderMarkdown(input: SessionNotesInput): string {
  const {
    engineerName,
    division,
    productName,
    topicsCovered,
    openQuestions,
    xpEarned,
    nextSteps,
    freeformNotes,
    language,
  } = input;

  const date = new Date().toISOString();
  const nameDisplay = engineerName ?? "Unknown Engineer";

  return `# Onboarding Session Notes
**Engineer:** ${nameDisplay}
**Product:** ${productName} (${division})
**Date:** ${date}
**Language:** ${language === "id" ? "Bahasa Indonesia" : "English"}
**XP Earned:** ⚡ ${xpEarned} XP

---

## Topics Covered
${topicsCovered.length > 0 ? topicsCovered.map((t) => `- ${t}`).join("\n") : "_None recorded_"}

## Open Questions
${openQuestions.length > 0 ? openQuestions.map((q) => `- ${q}`).join("\n") : "_None_"}

## Next Steps
${nextSteps.length > 0 ? nextSteps.map((s) => `- [ ] ${s}`).join("\n") : "_None_"}

${freeformNotes ? `## Additional Notes\n${freeformNotes}` : ""}

---
_Generated by mcp-onboarding_
`;
}

export async function saveSessionNotes(input: SessionNotesInput): Promise<SaveNotesResult> {
  const sessionDir = join(input.repoPath, ".onboarding-sessions");

  try {
    await mkdir(sessionDir, { recursive: true });
  } catch (e) {
    return { savedPath: "", success: false, error: `Could not create sessions dir: ${e}` };
  }

  const datePart = formatDate();
  const namePart = input.engineerName ? slugify(input.engineerName) : "anonymous";
  const fileName = `${datePart}-${namePart}.md`;
  const filePath = join(sessionDir, fileName);

  const content = renderMarkdown(input);

  try {
    await writeFile(filePath, content, "utf-8");
    return { savedPath: filePath, success: true };
  } catch (e) {
    return { savedPath: "", success: false, error: `Write failed: ${e}` };
  }
}

export async function listPastSessions(repoPath: string): Promise<string[]> {
  const sessionDir = join(repoPath, ".onboarding-sessions");
  try {
    const files = await readdir(sessionDir);
    return files.filter((f) => f.endsWith(".md")).sort().reverse();
  } catch {
    return [];
  }
}
